### ISSUE TITLE
Cannot connect to Amcrest NVR

### ISSUE THREAD

**Issue by bryeartem** [psyciknz/CameraEvents#17]
I have a newer NV4216E-AI NVR and cannot connect with message "Invalid Authority" 
The API seems identical to previous models, and I can also use /cgi-bin/eventManager.cgi?action=attach&codes=[VideoMotion] and get the expected Code=VideoMotion,Start/Stop etc when using in browser.. it seems it is not authenticating properly as I get this message:
`INFO:__main__:Connected to MQTT OK Returned code=0
2020-09-10 16:03:59,284 - __main__ - INFO - Connected to MQTT OK Returned code=0
INFO:__main__:Connected to MQTT OK Returned code=0
2020-09-10 16:04:01,179 - __main__ - DEBUG - [NVR]: Error
Invalid Authority!

DEBUG:__main__:[NVR]: Error
Invalid Authority!

2020-09-10 16:04:01,180 - __main__ - DEBUG - [NVR] OnDisconnect(Success)
DEBUG:__main__:[NVR] OnDisconnect(Success)
`
I'm hoping you could tell me what I could do to troubleshoot the issue.  I read in a zoneminder forum about issues with PTZ commands needing to be sent twice as it would fail for authentication the first time then work on the second.  I really don't know where to start..

**Comment by psyciknz** [comment]
What authentication method are you using?  I think if the camera (nvr)
config you can set basic or digest.  If nothing set, it is probably
defaulting to basic.

**Comment by bryeartem** [comment]
So I verified and it was on digest, I did try basic last night once I realized it wasn’t connecting.  Is there a way to see more detail that just the “Invalid Authority” message?

**Comment by psyciknz** [comment]
Not really no......  it's just using curl in the background.    Maybe just
try going to the event url via curl and seeing if you can login or not.

**Comment by bryeartem** [comment]
My apologies, I guess I really went down the rabbit-hole troubleshooting this one... and didn't follow my own normal steps for not making multiple changes when troubleshooting... I just assumed it wasn't working and ended up jacking up a few things... ultimately my cameras had "incorrect" names from what they used to be in MQTT, but I must have changed my config.ini before I realized and started a domino effect as I also had to hardcode the config.ini back when I first started using this.. so the "Invalid Authority" was because it was using a config.ini that wasn't populated fully and didn't have my username and password.. <embarrassed>. 
But, anyway, thanks for your awesome component as nobody makes anything to handle the NVR motion, just individual cameras... your work has been an integral part of my home automation system...! 👍
