### ISSUE TITLE
Payload error in event VideoMotion when stop.

### ISSUE THREAD

**Issue by jbolanosg** [psyciknz/CameraEvents#22]
I believe that it is a error the next line:
https://github.com/psyciknz/CameraEvents/blob/ed54c3e890376fc3fa0d75d5413fc4d275bbd64e/CameraEvents.py#L669

![imagen](https://user-images.githubusercontent.com/22716962/105425418-5bdac800-5c17-11eb-9096-4a3c1aaba723.png)

The payload must be OFF

**Comment by psyciknz** [comment]
Yes looks like you're right.  I'll make a fix for that.

**Comment by psyciknz** [comment]
Should be solved....BUT, for some reason i can't create arm and arm64 docker images at the moment with Travis.  So if you use those you'll have download and build yourself.  Sorry.  Something in a pip command is failing.

**Comment by jbolanosg** [comment]
I already did it...i Already have a the new image ARM64 with your correction.

**Comment by psyciknz** [comment]
Did you manually build?  I'll have to figure out a new travis flow

**Comment by jbolanosg** [comment]
Yes with this steps:
1. cd /tmp
2. git clone https://github.com/psyciknz/CameraEvents
3. cd CameraEvents/

4. docker build -t  psyciknz/cameraevents:latest . 
5. docker run --restart unless-stopped -d  --env TZ=America/Bogota -v /appdata/cameraevents:/opt/cameraevents/conf --name dahua-cameraevents psyciknz/cameraevents:latest

My machine is a Tv Box with Ubuntu 20.04 and Amlogic S905X2 processor (ARM64).
