### ISSUE TITLE
[enhancement] Patch to add auth support for MQTT

### ISSUE THREAD

**Issue by ghost** [psyciknz/CameraEvents#4]
This should add support for broker authentication. Make sure 'user' and 'password' are present in the right section for the config.ini file.

No error checking added, err=5 or so when auth fails. Quick hack that works for me.

```
diff --git a/CameraEvents.py b/CameraEvents.py
index f5f632e..21adc39 100644
--- a/CameraEvents.py
+++ b/CameraEvents.py
@@ -312,6 +312,7 @@ class DahuaEventThread(threading.Thread):
         self.basetopic = mqtt["basetopic"]
 
         self.client = paho.Client("CameraEvents-" + socket.gethostname(), clean_session=True)
+        self.client.username_pw_set(mqtt["user"], mqtt["password"])
         self.client.on_connect = self.mqtt_on_connect
         self.client.on_disconnect = self.mqtt_on_disconnect
         self.client.message_callback_add(self.basetopic +"/+/picture",self.mqtt_on_picture_message)
@@ -529,6 +530,8 @@ if __name__ == '__main__':
         mqtt["IP"] = cp.get("MQTT Broker","IP")
         mqtt["port"] = cp.get("MQTT Broker","port")
         mqtt["basetopic"] = cp.get("MQTT Broker","BaseTopic")
+        mqtt["user"] = cp.get("MQTT Broker","user")
+        mqtt["password"] = cp.get("MQTT Broker","password")
         dahua_event = DahuaEventThread(mqtt,cameras)
 
         dahua_event.start()

```

**Comment by psyciknz** [comment]
Ok, I can look at adding that snippet

**Comment by oblogic7** [comment]
Any plans to merge this into master?  My MQTT broker requires authentication.  I'll be happy to fork and open a PR if you can approve it.

**Comment by psyciknz** [comment]
I've added this.   It's in the image-playback branch,  Any chance @oblogic7 can try it?  Though this branch did jump to python 3.7.2 as well....so unsure if that will impact - I don't know how you run it.

**Comment by oblogic7** [comment]
I was trying to run via docker image.  I'll manually checkout that branch and give it a test.  Do you have an ETA on when that branch may be merged and available on the docker image?

**Comment by psyciknz** [comment]
What architecture of an image?  Arm32, arm64 or amd64?  I can push a dev one for you you try (there's some other code in there as well, which is why I don't want to merge to master yet).

**Comment by oblogic7** [comment]
amd64

**Comment by psyciknz** [comment]
docker pull psyciknz/cameraevents:0.2.0-dev. @oblogic7

**Comment by oblogic7** [comment]
Pulled the image, but am running into the following error:
`2020-01-09 17:45:10,161 - __main__ - ERROR - Error starting:Failed to open/find all files`

Any ideas on that?  Volume is bound according to the screenshot below and `config.ini` file exists with full permissions.  Not sure why it isn't working.

![image](https://user-images.githubusercontent.com/453840/72092153-55f99980-32d7-11ea-8756-2f96b3cf0ab3.png)

**Comment by psyciknz** [comment]
Does it bomb out entirely, or does the container stay running?   If it stays running, exec into it and check the volumes.  But I don't think I played with anything there (though the python version was increased).

Did you note the change to the user name in the config file?
cp.get("MQTT Broker","user",fallback=None)
user - not username

**Comment by oblogic7** [comment]
I did notice that key changed, but I don't think it is a format issue.  It seems that it isn't finding the file at all.  I don't see any reason in the code why it wouldn't be working, so has to be a permission or binding issue.

**Comment by psyciknz** [comment]
There are exceptions when it doens't like the format of the .ini....but if it was that I think you'd have a bigger crash.

I think you migh right on permissions/binding.  Execing into the container should be able to point you in the right direction.

**Comment by oblogic7** [comment]
I've been able to get further along by removing the user specific lines from the dockerfile and rebuilding the image.  Still poking at it on the image-playback branch.  Will report back once I have it fully working with the changes that I made.

**Comment by oblogic7** [comment]
I was finally able to get things running on the image-playback branch with the greatly simplified dockerfile below.  I also needed to run the container with host network mode to allow connection to my broker.  Not sure if this dockerfile is compatible with all architectures you build for, but feel free to use it if it does.

```
FROM amd64/python:2.7.15-jessie

WORKDIR /opt/cameraevents

COPY . /opt/cameraevents

RUN pip install -r requirements.txt

# run process
CMD python CameraEvents.py
```

**Comment by psyciknz** [comment]
And that works?   I thought I’d updated the code for python 3.7 which means
it would fail in 2.7

**Comment by oblogic7** [comment]
I haven't seen any issues yet.   Just setup my IVS rules last night, so planning to test and start using the events today. Will let you know if I run into any issues, but there weren't any complaints about syntax.  The container has been running for 11 hours now without issue.

**Comment by valepe** [comment]
Hi,
I'd like to use this script as docker image on a Synology Nas with DSM 6.x.
Because my MQTT broker requires authentication can I use this image as it is?

**Comment by psyciknz** [comment]
This dev one yes.  Then if you confirm it’s ok, I’ll pr the code to master

**Comment by valepe** [comment]
Sorry for the delay but I'm busy with my family.
In next days I will try it. Only one question: since my cameras are in a different subnet, they aren't accessible from your docker image but NVR it is (its IP is in the main lan).
Does it report tripwire and intrusion alerts from cameras?

**Comment by psyciknz** [comment]
> Sorry for the delay but I'm busy with my family.
> In next days I will try it. Only one question: since my cameras are in a different subnet, they aren't accessible from your docker image but NVR it is (its IP is in the main lan).
> Does it report tripwire and intrusion alerts from cameras?

Yes, you point camera events at your NVR, and tell it it's an nvr (in the config).
```
[NVR]
host=192.168.1.108
protocol=http
name=NVR
**isNVR=True**
port=80
user=<nvruser>
pass=<nvrpassword>
auth=digest
events=VideoMotion,CrossLineDetection,AlarmLocal,VideoLoss,VideoBlind,CrossRegionDetection,FaceDetection
#channels=0:Garage|1:Backdoor|2:Backyard|3:Frontdoor|4:Ludlam
snapshotoffset=1
```

And there's an optional (I think it still works) channels, to name and number channels.  But the default is it will figure out all the attached cameras.

**Comment by valepe** [comment]
Ok, I just tried and it works but not as I like.
I'm trying the NVR with one camera only and CameraEvents connects to it and to my mqtt broker.
But when I tryed a input alarm on the NVR I saw these command on mqtt:
CameraEvents/CAM-05/NVR = AlarmLocal
Now two things that I don't know:
1) why the NVR is listed under the camera name?
2) the alarm doesn't turn off when I close the alarm connected to the NVR input (but I see in the NVR log that alarm goes off)
This becomes useless because my domotic hub knows when an alarm starts but not when it ends.

Can you help me?

My config reflects your example: I haven't listed the camera channels and I don't add the snapshotoffset

**Comment by valepe** [comment]
<img width="612" alt="Schermata 2020-02-12 alle 23 00 35" src="https://user-images.githubusercontent.com/47390680/74381371-90c98280-4deb-11ea-87c2-e28c1c517e3e.png">

This is the screenshot after I tried a tripwire alarm. It works but it doesn't report that it goes off

**Comment by valepe** [comment]
Little update. I'm using MQTT Explorer and I disconnect it then reconnected and all alarm are disappeared. Is this the behavior?
If yes, how can I integrate it in Home Assistant so it can know when an alarm is on and when is off?

But remains the issue of NVR under my camera name. What happens when I'll connect to the NVR all other cameras?

**Comment by psyciknz** [comment]
> Little update. I'm using MQTT Explorer and I disconnect it then reconnected and all alarm are disappeared. Is this the behavior?
> If yes, how can I integrate it in Home Assistant so it can know when an alarm is on and when is off?

I'll start with this one.  

Unsure if I have retain turned on for the message.  I'm assuming by what you say I don't.  But if Home assistant is looking at it, it should hold the last state until it gets a change (ie when cameraeveents restarts and an alarm is posted.  If no alarm is posted, then HA will continue to display the last state,

**Comment by psyciknz** [comment]
> Ok, I just tried and it works but not as I like.
> I'm trying the NVR with one camera only and CameraEvents connects to it and to my mqtt broker.
> But when I tryed a input alarm on the NVR I saw these command on mqtt:
> CameraEvents/CAM-05/NVR = AlarmLocal
> Now two things that I don't know:
> 
> 1. why the NVR is listed under the camera name?
> 2. the alarm doesn't turn off when I close the alarm connected to the NVR input (but I see in the NVR log that alarm goes off)
>    This becomes useless because my domotic hub knows when an alarm starts but not when it ends.
> 
> Can you help me?
> 
> My config reflects your example: I haven't listed the camera channels and I don't add the snapshotoffset

Techinically if you only have one camera, and it's channel 1 (or 0), you don't tell to tell the "camera" it's an NVR.  Thats said, I've not dealt with AlarmLocal as a state....is this an external alarm connected to a camera?  

How would you expect to see it?
CameraEvents/CAM-05/AlarmLocal?
```
self.client.publish(self.basetopic +"/" + Alarm["channel"] + "/" + Alarm["name"],Alarm["Code"])
```
This could be it, which is part of a fall through of events, which looks like it's posted the channel name (CAM-05) then the name of the device (NVR - from the config.ini). 

Where as an IVS event is
```
self.client.publish(self.basetopic +"/IVS/" + Alarm["channel"] ,regionText)
```

To be consistent, the fall through should be:
self.client.publish(self.basetopic +"/" + Alarm["Code"] +  " /" + Alarm["channel"] ,true|false)

**Comment by valepe** [comment]
> > Little update. I'm using MQTT Explorer and I disconnect it then reconnected and all alarm are disappeared. Is this the behavior?
> > If yes, how can I integrate it in Home Assistant so it can know when an alarm is on and when is off?
> 
> I'll start with this one.
> 
> Unsure if I have retain turned on for the message. I'm assuming by what you say I don't. But if Home assistant is looking at it, it should hold the last state until it gets a change (ie when cameraeveents restarts and an alarm is posted. If no alarm is posted, then HA will continue to display the last state,

Is It possible to have an alarm on and an alarm off topics? I saw in the log that cameraevents receives the start and stop messages

**Comment by valepe** [comment]
> > Ok, I just tried and it works but not as I like.
> > I'm trying the NVR with one camera only and CameraEvents connects to it and to my mqtt broker.
> > But when I tryed a input alarm on the NVR I saw these command on mqtt:
> > CameraEvents/CAM-05/NVR = AlarmLocal
> > Now two things that I don't know:
> > 
> > 1. why the NVR is listed under the camera name?
> > 2. the alarm doesn't turn off when I close the alarm connected to the NVR input (but I see in the NVR log that alarm goes off)
> >    This becomes useless because my domotic hub knows when an alarm starts but not when it ends.
> > 
> > Can you help me?
> > My config reflects your example: I haven't listed the camera channels and I don't add the snapshotoffset
> 
> Techinically if you only have one camera, and it's channel 1 (or 0), you don't tell to tell the "camera" it's an NVR. Thats said, I've not dealt with AlarmLocal as a state....is this an external alarm connected to a camera?
> 
> How would you expect to see it?
> CameraEvents/CAM-05/AlarmLocal?
> 

No, this alarm Is connected to alarm inputs of the NVR so I'm expect to see a tipici lime CameraEvents/NVR/AlarmLocal and then the number of the alarm input (my NVR has 4 inputs and 2 outputs) and the start and stop states

**Comment by psyciknz** [comment]
Hmm any ideas how I would similate that, to look at it?  Do I just need to jumper (make a circuit) the alarm input to trigger it?

Can you post this as a new issue.  I think the mqtt authentication is done.

**Comment by psyciknz** [comment]
Pushed to master #10
